### ISSUE TITLE
请问 win10 电脑执行的时候报 ORMError 是什么问题呢？

### ISSUE THREAD

**Issue by zhengxs2018** [Houfeng/cix#12]
* **Library Version:**
0.3.5

* **Operating System:**
Windows 10

* **Node Version:**
7.2.1

* **NPM Version:**
4.0.3

按照示例写了一个 DEMO，但是执行 cize 的时候出现了如下的错误

![image](https://cloud.githubusercontent.com/assets/7506913/22193212/bfc03d5e-e174-11e6-95f6-aefd66191d39.png)

ORM 出错是指我数据库没有配置吗？持续集成一般都需要一个数据库支持的吧，我电脑上安装了 mongodb, redis, mysql 这三种数据库，但是没有看到配置数据的介绍。

我是个人想本地搭建一个环境，我本地搭建了 npm 仓库，gitlab,  现在想再搭建一个 ci，主要是做实验性的插件（随时废弃，供学习使用）, 但是大神你这个是不是不支持 window 系统的，如果不支持能给我的回复吗？

**Comment by Houfeng** [comment]
cize 的定位是一个极轻量的 ci 服务，所以没有暴露数据库相关的配置，启动 cize 时会自动创建一个SQLite 数据库，用于存储 job 执行记录等相关数据。

目前，仅在 Linux 和 Mac 上测试过（test 目录中有相关单元测试），并未在 windows 进行相关测试。

**Comment by zhengxs2018** [comment]
哦，好吧，那可能是 windows 的问题吧，谢谢
